[package]
name = "rtext"
version = "0.1.0"
authors = ["Jean-Philippe Moresmau <jean-philippe.moresmau@asg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-slash = "0.1.1"